### ISSUE TITLE
Unable to submit: Object creation rate limit exceeded

### ISSUE THREAD

**Issue by benkulbertis** [anonymousbitcoin/sentinel#7]
Hi there, I'm getting the following issues running an anon masternode. The sentinel debug output shows: `Unable to submit: Object creation rate limit exceeded`

The node debug log shows `CGovernanceManager::MasternodeRateCheck -- Rate too high` and `Object submission rejected because of rate check failure (buffer updated)`.

Could this please be explained? Is this my issue or a bug? I have not received any masternode payments.

I am running sentinel via CRON every minute as shown in the documentation for this project.

Thank you!

**Comment by nlevo** [comment]
Please update sentinel to version [1.1.2](https://github.com/anonymousbitcoin/sentinel/releases/tag/v1.1.2).
